FROM golang:1.24 AS build
WORKDIR /src
COPY go.mod .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/proxy ./cmd/proxy

FROM gcr.io/distroless/base-debian12
COPY --from=build /out/proxy /proxy
USER 0:0
EXPOSE 8443
ENTRYPOINT ["/proxy"]

