name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v0.1.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build & push agent
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.agent
          push: true
          tags: |
            mosonyi/swarmcli-agent:${{ env.VERSION }}
            mosonyi/swarmcli-agent:latest

      - name: Build & push proxy
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.proxy
          push: true
          tags: |
            mosonyi/swarmcli-proxy:${{ env.VERSION }}
            mosonyi/swarmcli-proxy:latest
